"""
Pentagon numbers
Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is
minimised; what is the value of D?

a(3a−1)/2 - b(3b-1)/2 = c(3c-1)/2
a(3a−1)/2 + b(3b-1)/2 = d(3d-1)/2

a(3a−1) - b(3b-1) = c(3c-1)
a(3a−1) + b(3b-1) = d(3d-1)

3a^2−a - 3b^2−b = c(3c-1)
3a^2−a + 3b^2−b = d(3d-1)
"""

from timeit import default_timer
import lib


def main():
    pentagonals = set()
    result_found = False
    n = 0
    while not result_found:
        n += 1
        pj = (3 * (n ** 2) - n) / 2
        for pk in pentagonals:
            if pj - pk in pentagonals and lib.is_pentagonal(pj + pk):
                print('|{} − {}|'.format(pj, pk))
                print(abs(pj - pk))
                result_found = True
        pentagonals.add(pj)


if __name__ == '__main__':
    start = default_timer()
    main()
    print(u"Runtime: {0} ms".format((default_timer() - start) * 1000))